spring:
  application:
    name: normalizer

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: normalizer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "ch.studior2.buildingpermitmonitor.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
